import formal.Artin
import formal.Axler
import formal.Cambridge-Tripos
import formal.Dummit-Foote
import formal.Herstein
import formal.Ireland-Rosen
import formal.Munkers
import formal.Pough
import formal.Putnam
import formal.Rudin
import Shakarachi
